QUESTION_BANK = {
    "technical": {
        "Python": [
            "Explain the difference between list and tuple in Python. When would you use one over the other?",
            "What are Python decorators? Write a simple decorator that logs the execution time of a function.",
            "Explain how memory management works in Python, including garbage collection and reference counting.",
            "What is the difference between shallow copy and deep copy in Python? How do you perform each?",
            "How do generators and yield work in Python? What are their advantages over returning list?",
            "Explain the difference between `__init__` and `__new__` in Python class creation.",
            "What is method resolution order (MRO) in Python? How does it handle multiple inheritance?",
            "Explain the difference between multithreading and multiprocessing in Python. What is the Global Interpreter Lock (GIL)?",
            "What are context managers in Python? Explain two ways to implement a custom context manager.",
            "What is the difference between `is` and `==` in Python? Give examples where they produce different results.",
            "How does Python's `asyncio` work? What are coroutines, event loops, and tasks?",
            "Explain list comprehensions, dictionary comprehensions, and generator expressions with examples.",
            "What is the difference between args and kwargs? How are they unpacked?",
            "Explain exception handling in Python. What is the role of the `else` and `finally` blocks?",
            "How do you implement classmethods and staticmethods in Python? What are their differences?",
            "What are Python descriptors? How do they work under the hood?",
            "Explain the concept of monkey patching in Python. When is it useful and what are its risks?",
            "What is a lambda function in Python? What are its limitations?",
            "How do you handle file input/output in Python efficiently for large files?",
            "What is the difference between string interpolation (f-strings), `str.format()`, and `%` formatting?"
        ],
        "Java": [
            "Explain the difference between JDK, JRE, and JVM.",
            "What is the difference between `equals()` and `==` in Java?",
            "Explain the Java Garbage Collection process and the different GC algorithms (e.g. G1, ZGC).",
            "What is the difference between method overloading and method overriding in Java?",
            "Explain the OOP concepts: Encapsulation, Inheritance, Polymorphism, and Abstraction in Java.",
            "What is the difference between abstract class and interface in Java? When should you use which?",
            "Explain Exception Handling in Java. What is the difference between Checked and Unchecked Exceptions?",
            "What is the Java Memory Model? Explain Stack Memory vs Heap Memory.",
            "What is string pool in Java? Explain the difference between String, StringBuilder, and StringBuffer.",
            "How does the `HashMap` work internally in Java? What is collision resolution?",
            "Explain multithreading in Java. What is the difference between extending `Thread` and implementing `Runnable`?",
            "What is the role of `volatile` and `synchronized` keywords in Java concurrency?",
            "What are Generics in Java? Explain Type Erasure.",
            "Explain Java Streams API. What are intermediate and terminal operations?",
            "What are Lambda Expressions in Java? How do they relate to Functional Interfaces?",
            "What is reflection in Java? When would you use it, and what are its drawbacks?",
            "Explain the difference between fail-fast and fail-safe iterators in Java.",
            "What is ClassLoader in Java? Explain the different types of ClassLoaders.",
            "What is serialization in Java? How do you prevent a field from being serialized?",
            "Explain the double-checked locking pattern for Singleton in Java."
        ],
        "JavaScript": [
            "Explain the difference between `var`, `let`, and `const` in JavaScript.",
            "What is closure in JavaScript? Provide a practical example of its usage.",
            "Explain event delegation and how event bubbling and capturing work in DOM.",
            "What is prototype inheritance in JavaScript? How does it differ from class-based inheritance?",
            "Explain the JavaScript Event Loop, Call Stack, Callback Queue, Microtask Queue, and Web APIs.",
            "What is the difference between `==` and `===` in JavaScript?",
            "Explain the difference between `Promise.all`, `Promise.allSettled`, `Promise.any`, and `Promise.race`.",
            "What is the keyword `this` in JavaScript? How do `bind`, `call`, and `apply` modify its behavior?",
            "Explain hoisting in JavaScript with variables and functions.",
            "What is the difference between null and undefined in JavaScript?",
            "Explain arrow functions. How do they handle the `this` context compared to regular functions?",
            "What is debounce and throttle in JavaScript? Write a simple debounce function.",
            "Explain strict mode in JavaScript. What are its benefits?",
            "What are Generators in JavaScript? How do they work with the `yield` keyword?",
            "What is Shadow DOM in JavaScript and web components?",
            "How does asynchronous JavaScript work under the hood using Async/Await and Promises?",
            "Explain the difference between deep copying and shallow copying of objects in JS.",
            "What are modules in JavaScript? Explain the difference between CommonJS and ES6 imports/exports.",
            "Explain what is a closure-based module pattern in JavaScript.",
            "How does memory management and garbage collection (e.g. Mark-and-Sweep) work in JS?"
        ],
        "React": [
            "Explain the Virtual DOM in React and how the reconciliation process (Fiber) works.",
            "What is the difference between functional components and class components in React?",
            "Explain the component lifecycle methods in React (for both class components and hooks).",
            "What are React Hooks? Explain the rules of hooks.",
            "Explain `useEffect` hook. What does the dependency array do? How do clean-up functions work?",
            "What is the difference between `useMemo` and `useCallback`? When should you use them?",
            "Explain React Context API. When would you use it instead of state management libraries like Redux?",
            "What are controlled vs uncontrolled components in React?",
            "Explain how keys work in React lists and why using index as key is discouraged.",
            "What is the difference between state and props in React?",
            "Explain React.lazy and Suspense for code splitting.",
            "What are Higher-Order Components (HOCs) in React? Give an example.",
            "How does React handle events? What is SyntheticEvent?",
            "What are portals in React and when would you use them?",
            "Explain error boundaries in React and how they are implemented.",
            "What is custom hook in React? Write a simple hook for fetching data.",
            "Explain state batching in React 18+.",
            "What are Server Components in React (RSC)? How do they differ from Client Components?",
            "How do you optimize React application performance?",
            "Explain what is the difference between prop drilling and state lifting."
        ],
        "FastAPI": [
            "What is FastAPI? What are its key features and advantages over Flask or Django?",
            "Explain dependency injection in FastAPI. How does the `Depends` function work?",
            "How does FastAPI handle asynchronous requests? What is the difference between `async def` and regular `def`?",
            "Explain how FastAPI utilizes Pydantic for data validation and serialization.",
            "What is the role of Starlette and Uvicorn in the FastAPI ecosystem?",
            "How do you handle path parameters and query parameters in FastAPI endpoints?",
            "Explain how to manage database connections (e.g. SQLAlchemy sessions) efficiently in FastAPI using dependency injection.",
            "How do you handle exception handling and return custom error responses in FastAPI?",
            "Explain how to implement JWT authentication and authorization in a FastAPI application.",
            "What are FastAPI background tasks? When should you use them over Celery?",
            "How do you auto-generate OpenAPI / Swagger documentation in FastAPI? How do you customize it?",
            "How do you handle file uploads in FastAPI? What is the difference between `UploadFile` and `bytes`?",
            "What is middleware in FastAPI? How do you write a custom middleware?",
            "Explain CORS (Cross-Origin Resource Sharing) middleware in FastAPI and why it is important.",
            "How do you test a FastAPI application using `TestClient` and pytest?",
            "How do you handle configuration and environment variables in FastAPI using Pydantic Settings?",
            "What are sub-applications in FastAPI and how do you mount them?",
            "How do you implement web sockets in FastAPI for real-time communication?",
            "Explain query parameters validation and path parameters validation in FastAPI.",
            "How does FastAPI handle connection pooling for databases like PostgreSQL?"
        ],
        "SQL": [
            "Explain the difference between INNER JOIN, LEFT JOIN, RIGHT JOIN, and FULL OUTER JOIN.",
            "What is normalization in database design? Explain 1NF, 2NF, and 3NF.",
            "What is the difference between WHERE and HAVING clauses in SQL?",
            "Explain the concept of indexes in SQL. What is the difference between Clustered and Non-Clustered indexes?",
            "What are ACID properties in database transactions?",
            "Explain aggregate functions in SQL and the GROUP BY clause.",
            "What is a subquery? Explain the difference between correlated and non-correlated subqueries.",
            "What is the difference between primary key, foreign key, and unique key?",
            "Explain SQL window functions (e.g. `ROW_NUMBER()`, `RANK()`, `DENSE_RANK()`, `LEAD()`, `LAG()`).",
            "What is a database view? What are its benefits and when should you use a materialized view?",
            "Explain what is SQL injection and how you can prevent it.",
            "What are database transactions and how do you control them (e.g., COMMIT, ROLLBACK, SAVEPOINT)?",
            "What is the difference between DELETE, TRUNCATE, and DROP statements?",
            "Explain Referential Integrity and cascade constraints in SQL.",
            "What are triggers in database management? Give a common use case.",
            "Explain execution plan (EXPLAIN) in SQL and how it helps optimize slow queries.",
            "What is a stored procedure? How does it differ from a user-defined function?",
            "Explain database locks (Shared, Exclusive) and deadlock resolution.",
            "What is the difference between OLTP and OLAP databases?",
            "Explain database partitioning and sharding."
        ]
    },
    "hr": {
        "Tell me about yourself": [
            "Can you walk me through your background and career journey so far?",
            "How would your coworkers describe your work style and personality?",
            "Tell me about your journey into software engineering/tech.",
            "What are you currently working on or learning that excites you?",
            "What is something not on your resume that you'd like us to know about you?",
            "Can you give a brief elevator pitch about your professional skills?",
            "How do you balance your technical expertise with communication skills?",
            "Tell me about your most successful project and your role in it.",
            "How did you get started in this industry?",
            "What motivates you to perform your best at work?"
        ],
        "Why should we hire you?": [
            "What makes you the best fit for this specific position?",
            "How do your skills match the requirements of this role?",
            "What unique value or perspective can you bring to our team?",
            "Why do you want to work for our company specifically?",
            "Give me an example of how your skills solved a critical problem in a past job.",
            "Why are you looking to leave your current role?",
            "What do you hope to contribute to our engineering culture?",
            "How does this job align with your long-term career vision?",
            "Why should we choose you over other qualified candidates?",
            "What makes you stand out as a software engineer?"
        ],
        "Strengths?": [
            "What do you consider your greatest professional strength?",
            "How has your primary strength helped you succeed in a past project?",
            "What technical or soft skills are you most proud of?",
            "Tell me about a time you had to learn a new skill quickly to solve a problem.",
            "How do you handle working under tight deadlines?",
            "What is your approach to collaboration and mentoring others?",
            "Tell me about a time you went above and beyond your duties.",
            "How do you stay organized and manage your time effectively?",
            "What feedback do you most commonly receive from your managers?",
            "How do you approach complex problem-solving?"
        ],
        "Weaknesses?": [
            "What do you consider your greatest professional weakness?",
            "Tell me about a time you failed or made a mistake on a project, and what you learned.",
            "What is a skill or area you are actively working to improve?",
            "How do you handle constructive criticism or negative feedback?",
            "Tell me about a time you disagreed with a colleague or manager, and how you resolved it.",
            "How do you handle stress or burnout?",
            "What is a work habit you've had to change over the course of your career?",
            "Can you describe a project that did not go according to plan and how you handled it?",
            "What is something you find challenging in team environments?",
            "How do you handle tasks that are ambiguous or lack clear direction?"
        ],
        "Career Goals?": [
            "Where do you see yourself in five years?",
            "What are your short-term and long-term career objectives?",
            "What kind of professional growth opportunities are you looking for here?",
            "How do you plan to stay ahead of changing technologies in your field?",
            "Would you prefer a management track or an individual contributor (IC) track?",
            "What does success look like for you in this role?",
            "What is your dream job in tech and why?",
            "How do you define a great engineering team culture?",
            "What certifications or skills do you plan to acquire next?",
            "How does this company help you achieve your ultimate career aspirations?"
        ]
    }
}
